version: '3.8s'

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5232:5232"
    depends_on:
      - selenium

  selenium:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
