version: '3'

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5232:5000"
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
