from selenium.webdriver.common.by import By

add_new_expenses_locator = (By.XPATH, "(//button[@type='button'])[2]")
expenses_name_locator = (By.XPATH, "(//input[@id='name'])[2]")
expenses_category_locator = (By.XPATH, "(//input)[10]")
expenses_currency_locator = (By.XPATH, "(//input)[11]")
expenses_price_locator = (By.XPATH, "//div[@class='BottomCollapseBox']//div//div[@class='ant-row css-16v3ahg']//div[@class='ant-col ant-col-24 css-16v3ahg']//div[@class='ant-spin-nested-loading css-16v3ahg']//div[@class='ant-spin-container']//form[@class='ant-form ant-form-vertical css-16v3ahg']//div//input[@id='total']")
expenses_description_locator = (By.XPATH, "(//textarea[@id='description'])[2]")
expenses_reference_locator = (By.XPATH, "(//input[@id='ref'])[2]")
expenses_submit_locator = (By.XPATH, "(//button[@type='submit'])[2]")
expenses_success_submitted_locator = (By.XPATH, "//div[@class='ant-notification-notice-wrapper' and contains(@style, "
                                                "'transform: translate3d(0px, 0px, 0px);')]")
enter_expenses_name_alert_locator = (By.XPATH, "(//div[contains(text(),'Please enter Name')])[1]")
enter_expenses_category_alert_locator = (By.XPATH, "(//div[contains(text(),'Please enter Expense Category')])[1]")
enter_expenses_price_alert_locator = (By.XPATH, "(//div[contains(text(),'Please enter Total')])[1]")
expenses_first_option_menu = (By.XPATH, "//tbody/tr[2]/td[7]/span[1]//*[name()='svg']")
show_option_of_menu = (By.CSS_SELECTOR, "div[class='ant-dropdown css-16v3ahg ant-dropdown-placement-bottomLeft'] li:nth-child(1)")
name_show_label = (By.XPATH, "(//p)[2]")
expense_show_label = (By.XPATH, "(//p)[5]")
currency_show_label = (By.XPATH, "(//p)[8]")
total_show_label = (By.XPATH, "(//p)[11]")
description_show_label = (By.XPATH, "(//p)[14]")
ref_show_label = (By.XPATH, "(//p)[17]")
